### ISSUE TITLE
Website would be better if it showed info about tissue origins of cell types

### ISSUE THREAD

**Issue by NathanSkene** [neurogenomics/rare_disease_celltyping_apps#14]
E.g. while discussing with Prof Meyr, he wanted to know what tissue the "AFP ALB positive cells" come from... couldn't give him anything on this. Maybe we should have a way to click through to this info?

Maybe this will be less of a problem with the cell type names from the new dataset

**Comment by bschilder** [comment]
Some of the celltypes defined in DescartesHuman were unique to that dataset, thus marker-based names like  "AFP ALB positive cells". It's all described in the supp info of their paper, but i can add the Cell Ontology aligned definitions as well to provide better interpretability.

**Comment by bschilder** [comment]
Instead of manually assigned cell types to the tissue we think they should belong to (introduces bias), I used the metadata from the original scRNA-seq datasets and included it as a data object in `MSTExplorer`:

```R
MSTExplorer::tissue_maps
```

![Image](https://github.com/neurogenomics/rare_disease_celltyping_apps/assets/34280215/2db0381c-693a-48bd-9f68-8c54d58504b1)

You can then use this to compute the proportion of each cell type in each tissue, or the tissue in which each cell type is most commonly found:

```R
map <- MSTExplorer::map_tissue()
```



![Image](https://github.com/neurogenomics/rare_disease_celltyping_apps/assets/34280215/7d20f6d3-b3ca-4d55-ab7f-0a475743b832)
